### PR TITLE
Added NPM support

### PR DESCRIPTION
**Pull request by willemvb**
package.json added for NPM support

### CODE REVIEW

**Comment by guidobouman** [comment]
It's already in Bower and the jQuery ecosystem, do you really think it's a good idea to have a front-end library inside npm?

Other than that, looks good. Might need to document the different installation options in an extra installation section as well.

**Comment by willemvb** [comment]
NPM is great for front-end development and has replaced Bower for me. See eg. https://www.quora.com/Why-use-Bower-when-there-is-npm or http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging

**Comment by guidobouman** [comment]
https://www.npmjs.com/package/jquery-panelsnap

**Comment by willemvb** [comment]
:+1: thanks!

**Pull request merged**
